/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as protectedViralShortsRouteImport } from './routes/(protected)/viral-shorts'
import { Route as protectedSavedRouteImport } from './routes/(protected)/saved'
import { Route as protectedRisingChannelsRouteImport } from './routes/(protected)/rising-channels'
import { Route as protectedOverviewRouteImport } from './routes/(protected)/overview'
import { Route as protectedMonitorRouteImport } from './routes/(protected)/monitor'
import { Route as protectedDiscoverRouteImport } from './routes/(protected)/discover'
import { Route as protectedAlertsRouteImport } from './routes/(protected)/alerts'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedViralShortsRoute = protectedViralShortsRouteImport.update({
  id: '/viral-shorts',
  path: '/viral-shorts',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSavedRoute = protectedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedRisingChannelsRoute = protectedRisingChannelsRouteImport.update({
  id: '/rising-channels',
  path: '/rising-channels',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedOverviewRoute = protectedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedMonitorRoute = protectedMonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedDiscoverRoute = protectedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedAlertsRoute = protectedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => protectedRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/alerts': typeof protectedAlertsRoute
  '/discover': typeof protectedDiscoverRoute
  '/monitor': typeof protectedMonitorRoute
  '/overview': typeof protectedOverviewRoute
  '/rising-channels': typeof protectedRisingChannelsRoute
  '/saved': typeof protectedSavedRoute
  '/viral-shorts': typeof protectedViralShortsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/alerts': typeof protectedAlertsRoute
  '/discover': typeof protectedDiscoverRoute
  '/monitor': typeof protectedMonitorRoute
  '/overview': typeof protectedOverviewRoute
  '/rising-channels': typeof protectedRisingChannelsRoute
  '/saved': typeof protectedSavedRoute
  '/viral-shorts': typeof protectedViralShortsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(protected)/alerts': typeof protectedAlertsRoute
  '/(protected)/discover': typeof protectedDiscoverRoute
  '/(protected)/monitor': typeof protectedMonitorRoute
  '/(protected)/overview': typeof protectedOverviewRoute
  '/(protected)/rising-channels': typeof protectedRisingChannelsRoute
  '/(protected)/saved': typeof protectedSavedRoute
  '/(protected)/viral-shorts': typeof protectedViralShortsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/alerts'
    | '/discover'
    | '/monitor'
    | '/overview'
    | '/rising-channels'
    | '/saved'
    | '/viral-shorts'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/alerts'
    | '/discover'
    | '/monitor'
    | '/overview'
    | '/rising-channels'
    | '/saved'
    | '/viral-shorts'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(protected)'
    | '/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(protected)/alerts'
    | '/(protected)/discover'
    | '/(protected)/monitor'
    | '/(protected)/overview'
    | '/(protected)/rising-channels'
    | '/(protected)/saved'
    | '/(protected)/viral-shorts'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/viral-shorts': {
      id: '/(protected)/viral-shorts'
      path: '/viral-shorts'
      fullPath: '/viral-shorts'
      preLoaderRoute: typeof protectedViralShortsRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/saved': {
      id: '/(protected)/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof protectedSavedRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/rising-channels': {
      id: '/(protected)/rising-channels'
      path: '/rising-channels'
      fullPath: '/rising-channels'
      preLoaderRoute: typeof protectedRisingChannelsRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/overview': {
      id: '/(protected)/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof protectedOverviewRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/monitor': {
      id: '/(protected)/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof protectedMonitorRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/discover': {
      id: '/(protected)/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof protectedDiscoverRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/alerts': {
      id: '/(protected)/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof protectedAlertsRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface protectedRouteRouteChildren {
  protectedAlertsRoute: typeof protectedAlertsRoute
  protectedDiscoverRoute: typeof protectedDiscoverRoute
  protectedMonitorRoute: typeof protectedMonitorRoute
  protectedOverviewRoute: typeof protectedOverviewRoute
  protectedRisingChannelsRoute: typeof protectedRisingChannelsRoute
  protectedSavedRoute: typeof protectedSavedRoute
  protectedViralShortsRoute: typeof protectedViralShortsRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedAlertsRoute: protectedAlertsRoute,
  protectedDiscoverRoute: protectedDiscoverRoute,
  protectedMonitorRoute: protectedMonitorRoute,
  protectedOverviewRoute: protectedOverviewRoute,
  protectedRisingChannelsRoute: protectedRisingChannelsRoute,
  protectedSavedRoute: protectedSavedRoute,
  protectedViralShortsRoute: protectedViralShortsRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  protectedRouteRoute: protectedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
